name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [adservice, cartservice, checkoutservice, currencyservice, emailservice, frontend, loadgenerator, paymentservice, productcatalogservice, recommendationservice, shippingservice, shoppingassistantservice]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Environment Variables
        run: |
          echo "DOCKERHUB_USER=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USER/uche-repository/${{ matrix.service }}:$IMAGE_TAG ./src/${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USER/uche-repository/${{ matrix.service }}:$IMAGE_TAG

      - name: Save image tag for deploy workflow
        id: export-tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    outputs:
      image_tag: ${{ steps.export-tag.outputs.image_tag }}
