name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # The matrix runs 12 parallel jobs, one for each service.
    strategy:
      matrix:
        service: [adservice, cartservice, checkoutservice, currencyservice, emailservice, frontend, loadgenerator, paymentservice, productcatalogservice, recommendationservice, shippingservice, shoppingassistantservice]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Use the official setup-buildx action for improved Docker building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          # Define the context (where the Dockerfile is located)
          context: ./src/${{ matrix.service }}
          # Use the latest tag and the commit SHA for tagging
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uche-repository/${{ matrix.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/uche-repository/${{ matrix.service }}:latest
          push: true
          # Enable caching for faster rebuilds
          cache-from: type=gha
          cache-to: type=gha,mode=max

# No job 'outputs' are needed here, as the tag is always available via ${{ github.sha }}

