name: Build & Push Docker Images

on:
# ... (trigger configuration remains the same)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [adservice, cartservice, checkoutservice, currencyservice, emailservice, frontend, loadgenerator, paymentservice, productcatalogservice, recommendationservice, shippingservice, shoppingassistantservice]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # --- 1. SETUP BUILDX (NEW REQUIRED STEP) ---
      # This enables the 'container' driver which supports GHA caching.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/${{ matrix.service }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uche-repository/${{ matrix.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/uche-repository/${{ matrix.service }}:latest
          push: true
          # GHA caching will now work because Buildx is configured correctly.
          cache-from: type=gha
          cache-to: type=gha,mode=max

